export type DelegateFile = {
  slug: string;
  name: string;
  district: string;
  locality: string;
  tax?: string;
  energy?: string;
};

/** Only members with a paper on disk. Add a row when the next file exists. */
export const DELEGATE_FILES: DelegateFile[] = [
  {
    slug: "hope-hd1",
    name: "Patrick A. Hope",
    district: "HD-1",
    locality: "Arlington (part)",
    tax: "/files/delegates/hope-hd1-tax.pdf",
  },
  {
    slug: "mcclure-hd2",
    name: "Adele Y. McClure",
    district: "HD-2",
    locality: "Arlington (part)",
    tax: "/files/delegates/mcclure-hd2-tax.pdf",
  },
  {
    slug: "lopez-hd3",
    name: "Alfonso H. Lopez",
    district: "HD-3",
    locality: "Arlington (part); Alexandria (part)",
    tax: "/files/delegates/lopez-hd3-tax.pdf",
  },
  {
    slug: "herring-hd4",
    name: "Charniele L. Herring",
    district: "HD-4",
    locality: "Fairfax (part); Alexandria (part)",
    tax: "/files/delegates/herring-hd4-tax.pdf",
  },
  {
    slug: "mcpike-hd5",
    name: "Kirk McPike",
    district: "HD-5",
    locality: "Alexandria (part)",
    tax: "/files/delegates/mcpike-hd5-tax.pdf",
  },
  {
    slug: "sullivan-hd6",
    name: 'Richard C. "Rip" Sullivan, Jr.',
    district: "HD-6",
    locality: "Fairfax (part)",
    tax: "/files/delegates/sullivan-hd6-tax.pdf",
  },
  {
    slug: "keys-gamarra-hd7",
    name: "Karen Keys-Gamarra",
    district: "HD-7",
    locality: "Fairfax (part)",
    tax: "/files/delegates/keys-gamarra-hd7-tax.pdf",
  },
  {
    slug: "shin-hd8",
    name: "Irene Shin",
    district: "HD-8",
    locality: "Fairfax County / Herndon",
    tax: "/files/delegates/shin-hd8-tax.pdf",
  },
  {
    slug: "delaney-hd9",
    name: "Karrie K. Delaney",
    district: "HD-9",
    locality: "Fairfax (part)",
    tax: "/files/delegates/delaney-hd9-tax.pdf",
  },
  {
    slug: "helmer-hd10",
    name: "Dan I. Helmer",
    district: "HD-10",
    locality: "Fairfax (part)",
    tax: "/files/delegates/helmer-hd10-tax.pdf",
  },
  {
    slug: "bulova-hd11",
    name: "Gretchen M. Bulova",
    district: "HD-11",
    locality: "Fairfax (part); City of Fairfax",
    tax: "/files/delegates/bulova-hd11-tax.pdf",
  },
  {
    slug: "seibold-hd12",
    name: "Holly M. Seibold",
    district: "HD-12",
    locality: "Fairfax (part)",
    tax: "/files/delegates/seibold-hd12-tax.pdf",
  },
  {
    slug: "simon-hd13",
    name: "Marcus B. Simon",
    district: "HD-13",
    locality: "Fairfax (part); City of Falls Church",
    tax: "/files/delegates/simon-hd13-tax.pdf",
  },
  {
    slug: "watts-hd14",
    name: "Vivian E. Watts",
    district: "HD-14",
    locality: "Fairfax (part)",
    tax: "/files/delegates/watts-hd14-tax.pdf",
  },
  {
    slug: "cohen-hd15",
    name: "Laura Jane Cohen",
    district: "HD-15",
    locality: "Fairfax (part)",
    tax: "/files/delegates/cohen-hd15-tax.pdf",
  },
  {
    slug: "krizek-hd16",
    name: "Paul E. Krizek",
    district: "HD-16",
    locality: "Fairfax (part)",
    tax: "/files/delegates/krizek-hd16-tax.pdf",
  },
  {
    slug: "mcguire-hd17",
    name: "Garrett McGuire",
    district: "HD-17",
    locality: "Fairfax (part)",
    tax: "/files/delegates/mcguire-hd17-tax.pdf",
  },
  {
    slug: "tran-hd18",
    name: "Kathy K.L. Tran",
    district: "HD-18",
    locality: "Fairfax (part)",
    tax: "/files/delegates/tran-hd18-tax.pdf",
  },
  {
    slug: "henson-hd19",
    name: "Rozia A. Henson, Jr.",
    district: "HD-19",
    locality: "Fairfax (part); Prince William (part)",
    tax: "/files/delegates/henson-hd19-tax.pdf",
  },
  {
    slug: "thomas-hd21",
    name: "Joshua E. Thomas",
    district: "HD-21",
    locality: "Prince William (part)",
    tax: "/files/delegates/thomas-hd21-tax.pdf",
  },
  {
    slug: "guzman-hd22",
    name: "Elizabeth R. Guzman",
    district: "HD-22",
    locality: "Prince William (part)",
    tax: "/files/delegates/guzman-hd22-tax.pdf",
  },
  {
    slug: "franklin-hd23",
    name: "Margaret A. Franklin",
    district: "HD-23",
    locality: "Prince William (part); Stafford (part)",
    tax: "/files/delegates/franklin-hd23-tax.pdf",
  },
  {
    slug: "torian-hd24",
    name: "Luke E. Torian",
    district: "HD-24",
    locality: "Prince William (part)",
    tax: "/files/delegates/torian-hd24-tax.pdf",
  },
  {
    slug: "sewell-hd25",
    name: "Briana D. Sewell",
    district: "HD-25",
    locality: "Prince William (part)",
    tax: "/files/delegates/sewell-hd25-tax.pdf",
  },
  {
    slug: "rasoul-hd38",
    name: "Sam Rasoul",
    district: "HD-38",
    locality: "City of Roanoke (part)",
    tax: "/files/delegates/rasoul-hd38-tax.pdf",
  },
  {
    slug: "singh-hd26",
    name: 'Jas Jeet "JJ" Singh',
    district: "HD-26",
    locality: "Loudoun County",
    tax: "/files/delegates/singh-hd26-tax.pdf",
    energy: "/files/delegates/singh-hd26-energy.pdf",
  },
  {
    slug: "reaser-hd27",
    name: "Atoosa R. Reaser",
    district: "HD-27",
    locality: "Loudoun County",
    tax: "/files/delegates/reaser-hd27-tax.pdf",
    energy: "/files/delegates/reaser-hd27-energy.pdf",
  },
  {
    slug: "reid-hd28",
    name: "David A. Reid",
    district: "HD-28",
    locality: "Loudoun County",
    tax: "/files/delegates/reid-hd28-tax.pdf",
    energy: "/files/delegates/reid-hd28-energy.pdf",
  },
  {
    slug: "martinez-hd29",
    name: 'Fernando J. "Marty" Martinez',
    district: "HD-29",
    locality: "Loudoun County",
    tax: "/files/delegates/martinez-hd29-tax.pdf",
  },
  {
    slug: "mcauliff-hd30",
    name: "John Chilton McAuliff",
    district: "HD-30",
    locality: "Loudoun County",
    tax: "/files/delegates/mcauliff-hd30-tax.pdf",
    energy: "/files/delegates/mcauliff-hd30-energy.pdf",
  },
];
