export type DelegateFile = {
  slug: string;
  name: string;
  district: string;
  locality: string;
  tax?: string;
  energy?: string;
};

/** Only members with a paper on disk. Add a row when the next file exists. */
export const DELEGATE_FILES: DelegateFile[] = [
{
    slug: "hope-hd1",
    name: "Patrick A. Hope",
    district: "HD-1",
    locality: "Arlington (part)",
    tax: "/files/delegates/hope-hd1-tax.pdf",
  },
{
    slug: "mcclure-hd2",
    name: "Adele Y. McClure",
    district: "HD-2",
    locality: "Arlington (part)",
    tax: "/files/delegates/mcclure-hd2-tax.pdf",
  },
{
    slug: "lopez-hd3",
    name: "Alfonso H. Lopez",
    district: "HD-3",
    locality: "Arlington (part); Alexandria (part)",
    tax: "/files/delegates/lopez-hd3-tax.pdf",
  },
{
    slug: "herring-hd4",
    name: "Charniele L. Herring",
    district: "HD-4",
    locality: "Fairfax (part); Alexandria (part)",
    tax: "/files/delegates/herring-hd4-tax.pdf",
  },
{
    slug: "mcpike-hd5",
    name: "Kirk McPike",
    district: "HD-5",
    locality: "Alexandria (part)",
    tax: "/files/delegates/mcpike-hd5-tax.pdf",
  },
{
    slug: "sullivan-hd6",
    name: 'Richard C. "Rip" Sullivan, Jr.',
    district: "HD-6",
    locality: "Fairfax (part)",
    tax: "/files/delegates/sullivan-hd6-tax.pdf",
  },
{
    slug: "keys-gamarra-hd7",
    name: "Karen Keys-Gamarra",
    district: "HD-7",
    locality: "Fairfax (part)",
    tax: "/files/delegates/keys-gamarra-hd7-tax.pdf",
  },
{
    slug: "shin-hd8",
    name: "Irene Shin",
    district: "HD-8",
    locality: "Fairfax County / Herndon",
    tax: "/files/delegates/shin-hd8-tax.pdf",
  },
{
    slug: "delaney-hd9",
    name: "Karrie K. Delaney",
    district: "HD-9",
    locality: "Fairfax (part)",
    tax: "/files/delegates/delaney-hd9-tax.pdf",
  },
{
    slug: "helmer-hd10",
    name: "Dan I. Helmer",
    district: "HD-10",
    locality: "Fairfax (part)",
    tax: "/files/delegates/helmer-hd10-tax.pdf",
  },
{
    slug: "bulova-hd11",
    name: "Gretchen M. Bulova",
    district: "HD-11",
    locality: "Fairfax (part); City of Fairfax",
    tax: "/files/delegates/bulova-hd11-tax.pdf",
  },
{
    slug: "seibold-hd12",
    name: "Holly M. Seibold",
    district: "HD-12",
    locality: "Fairfax (part)",
    tax: "/files/delegates/seibold-hd12-tax.pdf",
  },
{
    slug: "simon-hd13",
    name: "Marcus B. Simon",
    district: "HD-13",
    locality: "Fairfax (part); City of Falls Church",
    tax: "/files/delegates/simon-hd13-tax.pdf",
  },
{
    slug: "watts-hd14",
    name: "Vivian E. Watts",
    district: "HD-14",
    locality: "Fairfax (part)",
    tax: "/files/delegates/watts-hd14-tax.pdf",
  },
{
    slug: "cohen-hd15",
    name: "Laura Jane Cohen",
    district: "HD-15",
    locality: "Fairfax (part)",
    tax: "/files/delegates/cohen-hd15-tax.pdf",
  },
{
    slug: "krizek-hd16",
    name: "Paul E. Krizek",
    district: "HD-16",
    locality: "Fairfax (part)",
    tax: "/files/delegates/krizek-hd16-tax.pdf",
  },
{
    slug: "mcguire-hd17",
    name: "Garrett McGuire",
    district: "HD-17",
    locality: "Fairfax (part)",
    tax: "/files/delegates/mcguire-hd17-tax.pdf",
  },
{
    slug: "tran-hd18",
    name: "Kathy K.L. Tran",
    district: "HD-18",
    locality: "Fairfax (part)",
    tax: "/files/delegates/tran-hd18-tax.pdf",
  },
{
    slug: "henson-hd19",
    name: "Rozia A. Henson, Jr.",
    district: "HD-19",
    locality: "Fairfax (part); Prince William (part)",
    tax: "/files/delegates/henson-hd19-tax.pdf",
  },
{
    slug: "thomas-hd21",
    name: "Joshua E. Thomas",
    district: "HD-21",
    locality: "Prince William (part)",
    tax: "/files/delegates/thomas-hd21-tax.pdf",
  },
{
    slug: "guzman-hd22",
    name: "Elizabeth R. Guzman",
    district: "HD-22",
    locality: "Prince William (part)",
    tax: "/files/delegates/guzman-hd22-tax.pdf",
  },
{
    slug: "franklin-hd23",
    name: "Margaret A. Franklin",
    district: "HD-23",
    locality: "Prince William (part); Stafford (part)",
    tax: "/files/delegates/franklin-hd23-tax.pdf",
  },
{
    slug: "torian-hd24",
    name: "Luke E. Torian",
    district: "HD-24",
    locality: "Prince William (part)",
    tax: "/files/delegates/torian-hd24-tax.pdf",
  },
{
    slug: "sewell-hd25",
    name: "Briana D. Sewell",
    district: "HD-25",
    locality: "Prince William (part)",
    tax: "/files/delegates/sewell-hd25-tax.pdf",
  },
{
    slug: "singh-hd26",
    name: 'Jas Jeet "JJ" Singh',
    district: "HD-26",
    locality: "Loudoun County",
    tax: "/files/delegates/singh-hd26-tax.pdf",
    energy: "/files/delegates/singh-hd26-energy.pdf",
  },
{
    slug: "reaser-hd27",
    name: "Atoosa R. Reaser",
    district: "HD-27",
    locality: "Loudoun County",
    tax: "/files/delegates/reaser-hd27-tax.pdf",
    energy: "/files/delegates/reaser-hd27-energy.pdf",
  },
{
    slug: "reid-hd28",
    name: "David A. Reid",
    district: "HD-28",
    locality: "Loudoun County",
    tax: "/files/delegates/reid-hd28-tax.pdf",
    energy: "/files/delegates/reid-hd28-energy.pdf",
  },
{
    slug: "martinez-hd29",
    name: 'Fernando J. "Marty" Martinez',
    district: "HD-29",
    locality: "Loudoun County",
    tax: "/files/delegates/martinez-hd29-tax.pdf",
  },
{
    slug: "mcauliff-hd30",
    name: "John Chilton McAuliff",
    district: "HD-30",
    locality: "Loudoun County",
    tax: "/files/delegates/mcauliff-hd30-tax.pdf",
    energy: "/files/delegates/mcauliff-hd30-energy.pdf",
  },
{
    slug: "rasoul-hd38",
    name: "Sam Rasoul",
    district: "HD-38",
    locality: "City of Roanoke (part)",
    tax: "/files/delegates/rasoul-hd38-tax.pdf",
  },
{
    slug: "franklin-hd41",
    name: "Lily V. Franklin",
    district: "HD-41",
    locality: "Montgomery (part); Roanoke (part)",
    tax: "/files/delegates/franklin-hd41-tax.pdf",
  },
{
    slug: "callsen-hd54",
    name: "Katrina Callsen",
    district: "HD-54",
    locality: "Albemarle (part); City of Charlottesville",
    tax: "/files/delegates/callsen-hd54-tax.pdf",
  },
{
    slug: "laufer-hd55",
    name: "Amy J. Laufer",
    district: "HD-55",
    locality: "Albemarle (part); Fluvanna (part); Louisa (part); Nelson (part)",
    tax: "/files/delegates/laufer-hd55-tax.pdf",
  },
{
    slug: "nivar-hd57",
    name: "May Nivar",
    district: "HD-57",
    locality: "Goochland (part); Henrico (part)",
    tax: "/files/delegates/nivar-hd57-tax.pdf",
  },
{
    slug: "willett-hd58",
    name: "Rodney T. Willett",
    district: "HD-58",
    locality: "Henrico (part)",
    tax: "/files/delegates/willett-hd58-tax.pdf",
  },
{
    slug: "carroll-hd64",
    name: "Stacey Annie Carroll",
    district: "HD-64",
    locality: "Stafford (part)",
    tax: "/files/delegates/carroll-hd64-tax.pdf",
  },
{
    slug: "cole-jg-hd65",
    name: "Joshua G. Cole",
    district: "HD-65",
    locality: "Spotsylvania (part); Stafford (part); City of Fredericksburg",
    tax: "/files/delegates/cole-jg-hd65-tax.pdf",
  },
{
    slug: "cole-n-hd66",
    name: "Nicole Cole",
    district: "HD-66",
    locality: "Caroline (part); Spotsylvania (part)",
    tax: "/files/delegates/cole-n-hd66-tax.pdf",
  },
{
    slug: "downey-hd69",
    name: "Mark C. Downey",
    district: "HD-69",
    locality: "Gloucester (part); James City (part); York (part); City of Newport News (part)",
    tax: "/files/delegates/downey-hd69-tax.pdf",
  },
{
    slug: "simonds-hd70",
    name: "Shelly A. Simonds",
    district: "HD-70",
    locality: "City of Newport News (part)",
    tax: "/files/delegates/simonds-hd70-tax.pdf",
  },
{
    slug: "anderson-hd71",
    name: "Jessica L. Anderson",
    district: "HD-71",
    locality: "James City (part); New Kent (part); City of Williamsburg",
    tax: "/files/delegates/anderson-hd71-tax.pdf",
  },
{
    slug: "mehta-hd73",
    name: "Leslie Chambers Mehta",
    district: "HD-73",
    locality: "Chesterfield (part)",
    tax: "/files/delegates/mehta-hd73-tax.pdf",
  },
{
    slug: "dougherty-hd75",
    name: "Lindsey Dougherty",
    district: "HD-75",
    locality: "Chesterfield (part); Prince George (part); City of Hopewell",
    tax: "/files/delegates/dougherty-hd75-tax.pdf",
  },
{
    slug: "gardner-hd76",
    name: "Debra D. Gardner",
    district: "HD-76",
    locality: "Chesterfield (part)",
    tax: "/files/delegates/gardner-hd76-tax.pdf",
  },
{
    slug: "schmidt-hd77",
    name: "Charlie Schmidt",
    district: "HD-77",
    locality: "Chesterfield (part); City of Richmond (part)",
    tax: "/files/delegates/schmidt-hd77-tax.pdf",
  },
{
    slug: "carr-hd78",
    name: "Betsy B. Carr",
    district: "HD-78",
    locality: "City of Richmond (part)",
    tax: "/files/delegates/carr-hd78-tax.pdf",
  },
{
    slug: "cousins-hd79",
    name: "Rae Cousins",
    district: "HD-79",
    locality: "City of Richmond (part)",
    tax: "/files/delegates/cousins-hd79-tax.pdf",
  },
{
    slug: "levere-bolling-hd80",
    name: "Destiny LeVere Bolling",
    district: "HD-80",
    locality: "Henrico (part)",
    tax: "/files/delegates/levere-bolling-hd80-tax.pdf",
  },
{
    slug: "mcquinn-hd81",
    name: "Delores L. McQuinn",
    district: "HD-81",
    locality: "Charles City; Chesterfield (part); Henrico (part)",
    tax: "/files/delegates/mcquinn-hd81-tax.pdf",
  },
{
    slug: "pope-adams-hd82",
    name: "Kimberly Pope Adams",
    district: "HD-82",
    locality: "Dinwiddie (part); Prince George (part); Surry; City of Petersburg",
    tax: "/files/delegates/pope-adams-hd82-tax.pdf",
  },
{
    slug: "clark-hd84",
    name: "Nadarius E. Clark",
    district: "HD-84",
    locality: "Chesapeake (part); Isle of Wight (part); Cities of Franklin and Suffolk (part)",
    tax: "/files/delegates/clark-hd84-tax.pdf",
  },
{
    slug: "price-hd85",
    name: "Marcia S. \"Cia\" Price",
    district: "HD-85",
    locality: "City of Newport News (part)",
    tax: "/files/delegates/price-hd85-tax.pdf",
  },
{
    slug: "thornton-hd86",
    name: "Virgil Thornton",
    district: "HD-86",
    locality: "York (part); Cities of Hampton (part) and Poquoson",
    tax: "/files/delegates/thornton-hd86-tax.pdf",
  },
{
    slug: "ward-hd87",
    name: "Jeion A. Ward",
    district: "HD-87",
    locality: "City of Hampton (part)",
    tax: "/files/delegates/ward-hd87-tax.pdf",
  },
{
    slug: "scott-d-hd88",
    name: "Don Scott",
    district: "HD-88",
    locality: "City of Portsmouth (part)",
    tax: "/files/delegates/scott-d-hd88-tax.pdf",
  },
{
    slug: "carnegie-hd89",
    name: "Karen R. \"Kacey\" Carnegie",
    district: "HD-89",
    locality: "Cities of Chesapeake (part) and Suffolk (part)",
    tax: "/files/delegates/carnegie-hd89-tax.pdf",
  },
{
    slug: "hayes-hd91",
    name: "C.E. Cliff Hayes, Jr.",
    district: "HD-91",
    locality: "Cities of Chesapeake (part) and Portsmouth (part)",
    tax: "/files/delegates/hayes-hd91-tax.pdf",
  },
{
    slug: "anthony-hd92",
    name: "Bonita G. Anthony",
    district: "HD-92",
    locality: "Cities of Chesapeake (part) and Norfolk (part)",
    tax: "/files/delegates/anthony-hd92-tax.pdf",
  },
{
    slug: "glass-hd93",
    name: "Jackie H. Glass",
    district: "HD-93",
    locality: "City of Norfolk (part)",
    tax: "/files/delegates/glass-hd93-tax.pdf",
  },
{
    slug: "hernandez-hd94",
    name: "Phil M. Hernandez",
    district: "HD-94",
    locality: "City of Norfolk (part)",
    tax: "/files/delegates/hernandez-hd94-tax.pdf",
  },
{
    slug: "askew-hd95",
    name: "Alex Q. Askew",
    district: "HD-95",
    locality: "Cities of Norfolk (part) and Virginia Beach (part)",
    tax: "/files/delegates/askew-hd95-tax.pdf",
  },
{
    slug: "convirs-fowler-hd96",
    name: "Kelly K. Convirs-Fowler",
    district: "HD-96",
    locality: "City of Virginia Beach (part)",
    tax: "/files/delegates/convirs-fowler-hd96-tax.pdf",
  },
{
    slug: "feggans-hd97",
    name: "Michael B. Feggans",
    district: "HD-97",
    locality: "City of Virginia Beach (part)",
    tax: "/files/delegates/feggans-hd97-tax.pdf",
  },
];
