import type { Story } from "@/content/types";

export const INVESTIGATIONS: Story[] = [
  {
    slug: "lcps-public-comment-speaker-time",
    kind: "investigation",
    title: "LCPS Public Comment and Speaker Time",
    dek: "Staff’s own NoVA table puts Loudoun schools at 1 minute per speaker while peers sit at 2–3 and VSBA’s typical band is 2–5 — from the September 15, 2026 retreat packet.",
    date: "2026-09-11",
    displayDate: "September 11, 2026",
    topic: "Schools",
    kicker: "Loudoun",
    image: "/images/investigations/lcps-public-comment-speaker-time.png",
    imageAlt: "Cover chart — LCPS public-comment speaker time vs NoVA peers",
    access: "public",
    readMinutes: 8,
    body: [
      { type: "p", text: "Bottom line. The September 15, 2026 School Board Retreat packet does not announce a brand-new vote to cut speaker time. What it does put on the table is clearer than a press release: staff’s own Northern Virginia comparison, reviewed 9/9/26, lists Loudoun County Public Schools at one minute per speaker. Every NoVA school peer in that same table sits at two or three. The Virginia School Boards Association’s October 2025 Policy Page says boards typically allow two to five minutes. Loudoun’s own Board of Supervisors runs a two-minute minimum with a 90-minute overall public-comment window. LCPS is the shortest per-speaker slot in the packet. The agenda item itself carries no staff recommendation—only three attachments." },
      { type: "p", text: "Parents do not need a consultant deck to feel what one minute means at the mic. Name the child. Name the school. Name the problem. The clock is already eating the sentence. Short or shrinking speaker time is bad for parents because the School Board is often the only room where a working parent can put a curriculum, safety, budget, or policy problem on the public record before a vote. The staff comparison sheet also prints “Up to 5 minutes” on the next line; that line appears only on that county sheet and is not how the room runs—the operative cutoff parents experience is one minute." },
      { type: "p", text: "The PDF has the peer chart, the three BoardDocs attachments, VSBA’s typical 2–5 band, and the summer 2025 frequency proposals (Donohue once-a-month; LaBell split nights) labeled as proposed—not adopted. Through September 2026 practice the packet’s LCPS cadence row still reads two Tuesdays a month." },
    ],
    citations: [
      { id: "boarddocs-item", label: "LCPS BoardDocs — School Board Retreat item 5.05 Public Comment (Sep 15, 2026)", href: "https://go.boarddocs.com/vsba/loudoun/Board.nsf/goto?open&id=DWNNKB6046A6" },
      { id: "boarddocs-county", label: "Public Comments Comparison by County (reviewed 9/9/26)", href: "https://go.boarddocs.com/vsba/loudoun/Board.nsf/files/DXTHU94A26D7/$file/Public%20Comments%20Comparison%20by%20County%20(3).pdf" },
      { id: "boarddocs-vsba", label: "VSBA Policy Page — October 2025 (Open Meetings, Fair Voices)", href: "https://go.boarddocs.com/vsba/loudoun/Board.nsf/files/DXTKKD523958/$file/The%20Policy%20Page%20-%20VSBA%20Oct.%202025.pdf" },
    ],
    documents: [
      {
        id: "pdf",
        title: "LCPS Public Comment and Speaker Time (PDF)",
        href: "/files/investigations/lcps-public-comment-speaker-time.pdf",
        kind: "pdf",
      },
    ],
  },
  {
    slug: "why-loudoun-republicans-lost-2023-win-2027",
    kind: "investigation",
    title: "Why Loudoun Republicans Lost in 2023 and How They Win Seats in 2027",
    dek: "One reading of the returns — supervisors, school board, split tickets — written so the cause and the path are both clear.",
    date: "2026-09-09",
    displayDate: "September 9, 2026",
    topic: "Elections",
    kicker: "Loudoun",
    image: "/images/investigations/why-loudoun-republicans-lost-2023-win-2027.png",
    imageAlt: "Cover of Why Loudoun Republicans Lost in 2023 and How They Win Seats in 2027",
    access: "public",
    readMinutes: 12,
    body: [
      { type: "p", text: "This paper is for people who have to explain 2023 to a room and then decide what to do before November 2027. It is not a fundraising memo. Money is set aside as the main excuse because the same voters, on the same day, hired Republicans for sheriff, treasurer, commissioner, clerk, and prosecutor." },
      { type: "p", text: "Why they lost: Loudoun did not refuse Republicans. It refused a 2021 message, a split chair field, and first-time names in the east. Voters fired the old school board and still left Democrats the majority. They hired GOP cops and tax officers and kept a Democratic chair with 48.7 percent because the other 51 percent did not stand in one line." },
      { type: "p", text: "How they win: one chair nominee, two +7 supervisor races (Algonkian and Little River) with local names, hold Catoctin and Dulles, talk like the sheriff they already elect, and stop running cable news as a county platform. A 5–4 board is possible. A sweep is not what the returns describe. The PDF has the full scorecard, supervisor table, and seven how-to moves for 2027." },
    ],
    citations: [
      { id: "enr", label: "Virginia Department of Elections — Loudoun ENR, Nov. 7, 2023", href: "https://enr.elections.virginia.gov/" },
      { id: "elect", label: "Virginia Department of Elections", href: "https://www.elections.virginia.gov/" },
    ],
    documents: [
      {
        id: "pdf",
        title: "Why Loudoun Republicans Lost in 2023 and How They Win Seats in 2027 (PDF)",
        href: "/files/investigations/why-loudoun-republicans-lost-2023-win-2027.pdf",
        kind: "pdf",
      },
    ],
  },
  {
    slug: "2026-dem-va-constitution-conflicts",
    kind: "investigation",
    title: "2026 Democratic Agenda — Conflicts with the Virginia Constitution",
    dek: "Eighty Democratic chief-patron measures from the 2026 Regular Session that press, rewrite, or try to lock policy into Virginia’s charter. Article I first, then elections, then constitutional amendments.",
    date: "2026-09-09",
    displayDate: "September 9, 2026",
    topic: "Accountability",
    kicker: "Constitution",
    image: "/images/investigations/2026-dem-va-constitution-conflicts.png",
    imageAlt: "Cover of 2026 Democratic Agenda — Conflicts with the Virginia Constitution",
    access: "public",
    readMinutes: 18,
    body: [
      { type: "p", text: "Bottom line. In the 2026 session, Democratic chief patrons did not treat the Virginia Constitution as a fence. They treated it as clay. They moved bills that rewrite who may vote, who may carry a gun, who may speak near a clinic or a campaign ad, how schools and courthouses deal with immigration enforcement, and—when ordinary statute was not enough—they tried to lock preferred policy into the Constitution itself so the next Assembly cannot casually unwind it." },
      { type: "p", text: "This paper screens Democratic chief-patron measures that passed, were vetoed after passage, or were carried over to 2027. From a larger session universe, eighty bills make the analysis body. Across that set, Article I takes the most pressure, then Article II (elections), then Article XII (amendments that hard-wire policy). Guns, voting rules, speech, immigration posture in schools and courthouses, and local charters are the main attack lines." },
      { type: "p", text: "The PDF has the kitchen-table opening, six attack chapters with bill numbers, and the full eighty-row table—bill, status, patron, title, and why each measure conflicts with the Virginia Constitution. LIS bill numbers resolve on the official Legislative Information System." },
    ],
    citations: [
      { id: "lis", label: "Virginia Legislative Information System", href: "https://lis.virginia.gov" },
      { id: "const", label: "Constitution of Virginia", href: "https://law.lis.virginia.gov/constitution/" },
    ],
    documents: [
      {
        id: "pdf",
        title: "2026 Democratic Agenda — Conflicts with the Virginia Constitution (PDF)",
        href: "/files/investigations/2026-dem-va-constitution-conflicts.pdf",
        kind: "pdf",
      },
    ],
  },
  {
    slug: "subramanyam-va10-questions-2026",
    kind: "investigation",
    title: "Questions for Further Inquiry: Suhas Subramanyam (VA-10)",
    dek: "Fair questions on dollars claimed, a House Nay, overlaps with Sen. Lucas, disclosures, and what stays open. Questions only — not a dossier dump.",
    date: "2026-09-05",
    displayDate: "September 5, 2026",
    topic: "Accountability",
    kicker: "VA-10",
    image: "/images/investigations/subramanyam-va10-questions-2026.png",
    imageAlt: "Questions for Further Inquiry — Suhas Subramanyam, Virginia's 10th District",
    access: "public",
    readMinutes: 4,
    body: [
      { type: "p", text: "This sheet is questions and short concern framings only. It does not reprint ledgers, donor lists, dollar tables, or sealed-matter detail. Fair questions. Not smear." },
      { type: "h2", text: "1. Airport, chip, and project-funding dollars" },
      { type: "p", text: "Concern. Public announcements highlight large FAA and related dollar figures tied to district airports and other projects. Table listings and selection notices are one thing. Personal sole credit is another." },
      { type: "p", text: "Did he alone secure the FAA Airport Terminal Program dollars for Manassas and Dulles that his office highlights? Did he alone secure the Manassas CHIPS / Micron figure that appears in corporate and Commerce texts? Did he alone secure the House Community Project Funding lines attributed to him on the Appropriations table? Where does \"proud to support\" end and proven sole cause begin?" },
      { type: "h2", text: "2. The NDAA Nay and the Clerk title" },
      { type: "p", text: "Concern. On one House roll, the Clerk short title on the board that day named a veterans-disinter measure. The text Members actually passed under that roll was a House substitute that later carried as the annual defense policy bill." },
      { type: "p", text: "What exactly did he vote Nay on when the Clerk title said one thing and the passage object was the NDAA substitute? Should voters read that Nay against the short title on the board, or against the substitute text that became law? Is an \"anti-defense\" label fair from that single roll, or does the version lock matter?" },
      { type: "h2", text: "3. Shared sponsorship and floor overlap with Sen. Lucas" },
      { type: "p", text: "Concern. He and Sen. Louise Lucas appear together on some state bill sponsorship lists and on many of the same floor rolls. Shared paperwork is real. What it proves is limited." },
      { type: "p", text: "What does shared sponsorship on state bills prove — and what doesn't it? What do high agree counts on the floor prove — and what don't they? Does shared sponsorship equal a vote? Does agreeing on most rolls equal coordination or ideology?" },
      { type: "h2", text: "4. Shared campaign donors on state filings" },
      { type: "p", text: "Concern. Some of the same donor names show up on both of their state campaign filings. Names on paper are association. Coordination is a different claim." },
      { type: "p", text: "When the same donor name appears on both filings, is that association or coordination? Does a shared filing string prove direction, a deal, or a quid? Should state donor strings ever be blended with federal totals as if they were one pot?" },
      { type: "h2", text: "5. Casework dollar milestones" },
      { type: "p", text: "Concern. The office has published milestone claims about money returned to constituents through casework. Office press is one source. An independent agency ledger is another." },
      { type: "p", text: "Are the casework dollar milestones office claims, or amounts pinned to an independent ledger? Has any agency, IG, FOIA production, or Clerk ledger confirmed those totals? Until that exists, how should a voter weigh the milestone ladder?" },
      { type: "h2", text: "6. S2 Impact / BWAV disclosure" },
      { type: "p", text: "Concern. House financial disclosures name S2 Impact LLC and BWAV Family Office as filing strings. Disclosures document what was filed. They do not invent a client list or prove a legislative conflict." },
      { type: "p", text: "What is documented on the disclosure forms about S2 Impact and BWAV — and what is still open? Is a Colorado trade-name card the same organization as the Atlanta-addressed disclosure source? Do the disclosure lines, standing alone, prove a vote tied to energy or data-center legislation?" },
      { type: "h2", text: "7. Firefighter / AVFRD Form A" },
      { type: "p", text: "Concern. He has claimed volunteer firefighter / EMT service with Ashburn Volunteer Fire and Rescue. Published images OCR as a Form A termination recommendation. Published images are not the same as an authenticated personnel record." },
      { type: "p", text: "Is the published Form A image an authenticated AVFRD personnel record, or a published image whose authenticity the department has not confirmed? What is documented of his own claim versus what remains open on roster membership and service years? Should voters treat secondary termination reporting as proven separation without a department-authenticated file?" },
      { type: "h2", text: "8. Monitoring statement vs sealed call content" },
      { type: "p", text: "Concern. He has said that conversations with Sen. Lucas were monitored and has tied the timing to a redistricting peak. What he said publicly is one fact. What was on the calls — and why he was a party — is another." },
      { type: "p", text: "What exactly did he say about monitoring, and what remains sealed? Does his timing statement prove that redistricting caused the interception? Is \"why he was on the calls\" answered by public remarks, or still open?" },
    ],
    citations: [
      { id: "clerk", label: "U.S. House Clerk roll calls", href: "https://clerk.house.gov" },
      { id: "faa", label: "FAA Airport Terminal Program", href: "https://www.faa.gov" },
      { id: "lis", label: "Virginia Legislative Information System", href: "https://lis.virginia.gov" },
    ],
    documents: [
      {
        id: "pdf",
        title: "Questions for Further Inquiry — Suhas Subramanyam VA-10 (PDF)",
        href: "/files/investigations/subramanyam-va10-questions-2026.pdf",
        kind: "pdf",
      },
    ],
  },
  {
    slug: "va-illegal-immigrant-crime-2020-2026",
    kind: "investigation",
    title: "Virginia Illegal-Immigrant Crime Intelligence, 2020–2026",
    dek: "42 unique sourced cases in the Commonwealth. Women and children first. Not a statewide crime census.",
    date: "2026-08-22",
    displayDate: "August 22, 2026",
    topic: "Immigration",
    kicker: "Immigration",
    image: "/images/investigations/va-illegal-immigrant-crime-2020-2026.png",
    imageAlt: "Cover of Virginia Illegal-Immigrant Crime Intelligence, 2020-2026",
    access: "public",
    readMinutes: 22,
    body: [
      { type: "p", text: "A sourced listing of crimes in Virginia from 2020 through 2026 where the defendant’s immigration status is reported as illegal, unlawfully present, an ICE detainer, or a DHS or court statement." },
      { type: "p", text: "Unique cases after de-dupe: 42 (27 women and children, 15 other victims). Fifteen of those have a sourced got-off or light-sentence outcome. This is not a complete statewide census of every Virginia crime, and it is not a count of every immigrant. Alleged is not convicted." },
    ],
    citations: [
      { id: "ice", label: "U.S. Immigration and Customs Enforcement", href: "https://www.ice.gov" },
      { id: "dhs", label: "U.S. Department of Homeland Security", href: "https://www.dhs.gov" },
    ],
    documents: [
      {
        id: "pdf",
        title: "Virginia Illegal-Immigrant Crime Intelligence, 2020-2026 (PDF)",
        href: "/files/investigations/va-illegal-immigrant-crime-2020-2026.pdf",
        kind: "pdf",
      },
    ],
  },
  {
    slug: "loudoun-data-center-intelligence-history-2015-2025",
    kind: "investigation",
    title: "Loudoun County Data Center Intelligence History, 2015–2025",
    dek: "From Data Center Alley as an economic asset to a countywide locational regime. 224 data-center hits across 119 pages.",
    date: "2026-01-02",
    displayDate: "2015–2025",
    topic: "Energy",
    kicker: "Data centers",
    image: "/images/investigations/loudoun-data-center-intelligence-history-2015-2025.png",
    imageAlt: "Cover of Loudoun County Data Center Intelligence History, 2015-2025",
    access: "public",
    readMinutes: 12,
    body: [
      { type: "p", text: "A chronological political and policy intelligence review of Loudoun County Board of Supervisors records on data centers, 2015-2025. The source corpus is an 881-page merged action-report file." },
      { type: "p", text: "Loudoun did not simply turn against data centers. The record shows a decade-long move from permissive siting plus revenue optimization to location, compatibility, power delivery, and residential buffers. Data centers are load and tax base. They are not treated here as the cause of Virginia’s energy architecture." },
    ],
    citations: [
      { id: "loudoun", label: "Loudoun County Board of Supervisors", href: "https://www.loudoun.gov/bos" },
    ],
    documents: [
      {
        id: "pdf",
        title: "Loudoun County Data Center Intelligence History, 2015-2025 (PDF)",
        href: "/files/investigations/loudoun-data-center-intelligence-history-2015-2025.pdf",
        kind: "pdf",
      },
    ],
  },
  {
    slug: "loudoun-tax-intelligence-history-2015-2025",
    kind: "investigation",
    title: "Loudoun County Tax Intelligence History, 2015–2025",
    dek: "Board tax, budget, revenue, and relief records. 674 tax hits across 284 pages of a 1,828-page corpus.",
    date: "2026-01-01",
    displayDate: "2015–2025",
    topic: "Taxes",
    kicker: "Taxes",
    image: "/images/investigations/loudoun-tax-intelligence-history-2015-2025.png",
    imageAlt: "Cover of Loudoun County Tax Intelligence History, 2015-2025",
    access: "public",
    readMinutes: 8,
    body: [
      { type: "p", text: "A chronological political and fiscal intelligence review of Loudoun County Board of Supervisors tax, budget, revenue, and relief records, 2015-2025." },
      { type: "p", text: "The decade is tax-base engineering: pressure to reduce or equalize the real-property rate, growing reliance on business and data-center personal property, and targeted relief. High rate is not an ideology label. The useful unit is the specific instrument and vote." },
    ],
    citations: [
      { id: "loudoun", label: "Loudoun County Board of Supervisors", href: "https://www.loudoun.gov/bos" },
    ],
    documents: [
      {
        id: "pdf",
        title: "Loudoun County Tax Intelligence History, 2015-2025 (PDF)",
        href: "/files/investigations/loudoun-tax-intelligence-history-2015-2025.pdf",
        kind: "pdf",
      },
    ],
  },
  {
    slug: "va-energy-legislative-intelligence-2026",
    kind: "investigation",
    title: "Virginia Energy Legislative Intelligence Analysis",
    dek: "2025–2026 corpus, 2026 session snapshot. 195 energy-policy bills after incidental keyword matches were removed.",
    date: "2026-01-24",
    displayDate: "January 2026",
    topic: "Energy",
    kicker: "Energy",
    image: "/images/investigations/va-energy-legislative-intelligence-2026.png",
    imageAlt: "Cover of the Virginia Energy Legislative Intelligence Analysis",
    access: "public",
    readMinutes: 22,
    body: [
      { type: "p", text: "A political and policy intelligence review of Virginia energy legislation, grid policy, data-center demand, generation, utility regulation, and consumer impacts." },
      { type: "p", text: "The source corpus is 378 broad energy-keyword bill records. The analytic set is 195 direct or materially related energy-policy bills: 114 House measures and 81 Senate measures. Bill numbers in the paper link to the official Virginia LIS record." },
    ],
    citations: [
      { id: "lis", label: "Virginia Legislative Information System", href: "https://lis.virginia.gov" },
    ],
    documents: [
      {
        id: "pdf",
        title: "Virginia Energy Legislative Intelligence Analysis (PDF)",
        href: "/files/investigations/va-energy-legislative-intelligence-2026.pdf",
        kind: "pdf",
      },
    ],
  },
  {
    slug: "loudoun-delegation-taxpayer-burden-2026",
    kind: "investigation",
    title: "Loudoun Delegate Delegation: 2026 Expanded Taxpayer Burden",
    dek: "Singh, Reaser, Reid, Martinez, and McAuliff. 287 potentially tax and taxpayer-burden bills. 13 delegation splits.",
    date: "2026-01-01",
    displayDate: "2026",
    topic: "Taxes",
    kicker: "Taxes",
    image: "/images/investigations/loudoun-delegation-taxpayer-burden-2026.png",
    imageAlt: "Cover of the Loudoun delegation taxpayer-burden analysis",
    access: "public",
    readMinutes: 11,
    body: [
      { type: "p", text: "Five Loudoun House Democrats on one expanded taxpayer-burden universe: taxes, taxing authority, levies, assessments, fees, charges, surcharges, tolls, revenue mechanisms, relief, credits, and exemptions." },
      { type: "p", text: "The cover count is 287 expanded bills, 161 newly discovered against the prior screen, 121 common Yea/Nay events, and 13 delegation splits. High Yea is not an ideology label." },
    ],
    citations: [
      { id: "lis", label: "Virginia Legislative Information System", href: "https://lis.virginia.gov" },
    ],
    documents: [
      {
        id: "pdf",
        title: "Loudoun Delegate Delegation taxpayer-burden analysis (PDF)",
        href: "/files/investigations/loudoun-delegation-taxpayer-burden-2026.pdf",
        kind: "pdf",
      },
    ],
  },
  {
    slug: "va-green-energy-architecture-2020-2026",
    kind: "investigation",
    title: "Virginia's Green-Energy Architecture, 2020–2026",
    dek: "How a 2020 statutory framework became a larger, more complicated energy system.",
    date: "2026-08-23",
    displayDate: "August 23, 2026",
    topic: "Energy",
    kicker: "Energy",
    image: "/images/investigations/va-green-energy-architecture-2020-2026.png",
    imageAlt: "Cover of Virginia's Green-Energy Architecture, 2020–2026",
    access: "public",
    readMinutes: 8,
    body: [
      { type: "p", text: "Virginia did not enact one green-energy law and move on. In 2020 it created a statutory architecture — renewable mandates, generation retirements, offshore wind, storage, and carbon-market policy — and the years since have repeatedly modified, financed, challenged, accelerated, and expanded pieces of that architecture." },
      { type: "p", text: "Independent VPIP analysis from Virginia Code, LIS, SCC, JLARC, and EIA. Data centers are load on that architecture. They are not treated here as the cause of it." },
    ],
    citations: [
      { id: "lis", label: "Virginia Legislative Information System", href: "https://lis.virginia.gov" },
    ],
    documents: [
      {
        id: "pdf",
        title: "Virginia's Green-Energy Architecture, 2020–2026 (PDF)",
        href: "/files/investigations/va-green-energy-architecture-2020-2026.pdf",
        kind: "pdf",
      },
    ],
  },
];

export function investigationBySlug(slug: string) {
  return INVESTIGATIONS.find((s) => s.slug === slug);
}
