import type { LibraryItem } from "@/content/types";

export const LIBRARY_KINDS: { id: LibraryItem["kind"]; label: string }[] = [
  { id: "government", label: "Government" },
  { id: "news", label: "News" },
  { id: "research-tool", label: "Research tools" },
  { id: "tool", label: "Tools" },
];

/** Public doors from the desk source list. Official filings over summaries. Coverage notes stay in the shop. */
export const LIBRARY: LibraryItem[] = [
  {
    slug: "foia-desk",
    title: "Virginia FOIA desk",
    summary: "Draft a VFOIA letter against a named public body. Stored on this device. It does not file anything.",
    date: "2026-08-01",
    displayDate: "August 2026",
    kind: "tool",
    source: "A Guy on X",
    access: "public",
    tool: "/library/foia",
  },
  {
    slug: "vfoia-request-template",
    title: "VFOIA request template",
    summary: "Plain-text letter under Va. Code § 2.2-3700 et seq. Copy, fill, send from your own mail.",
    date: "2026-08-12",
    displayDate: "August 12, 2026",
    kind: "tool",
    source: "Virginia FOIA",
    access: "public",
    file: "/library/vfoia-request-template.txt",
  },
  {
    slug: "clerk-of-the-us-house-of-representatives-roll-call-votes",
    title: "Clerk of the US House of Representatives — Roll Call Votes",
    summary: "House roll-call votes.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Clerk of the US House of Representatives",
    access: "public",
    href: "https://clerk.house.gov/evs/",
  },
  {
    slug: "commonwealth-data-point",
    title: "Commonwealth Data Point",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Commonwealth Data Point",
    access: "public",
    href: "https://www.datapoint.apa.virginia.gov",
  },
  {
    slug: "commonwealth-data-point-downloadable-data-sets",
    title: "Commonwealth Data Point — Downloadable Data Sets",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Commonwealth Data Point",
    access: "public",
    href: "https://www.datapoint.apa.virginia.gov/legacyindex.php",
  },
  {
    slug: "commonwealth-of-virginia-official-website",
    title: "Commonwealth of Virginia — Official Website",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Commonwealth of Virginia",
    access: "public",
    href: "https://www.virginia.gov",
  },
  {
    slug: "congress-gov",
    title: "Congress.gov",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Congress.gov",
    access: "public",
    href: "https://www.congress.gov",
  },
  {
    slug: "eva-virginia-procurement-system",
    title: "eVA — Virginia Procurement System",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "eVA",
    access: "public",
    href: "https://eva.virginia.gov",
  },
  {
    slug: "fec-bulk-data-resources",
    title: "FEC — Bulk Data & Resources",
    summary: "Bulk FEC datasets.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "FEC",
    access: "public",
    href: "https://www.fec.gov/data/browse-data?tab=bulk-data",
  },
  {
    slug: "fec-candidate-raising",
    title: "FEC — Candidate Raising",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "FEC",
    access: "public",
    href: "https://www.fec.gov/data/browse-data?tab=raising",
  },
  {
    slug: "fec-candidate-spending",
    title: "FEC — Candidate Spending",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "FEC",
    access: "public",
    href: "https://www.fec.gov/data/browse-data?tab=spending",
  },
  {
    slug: "fec-candidates",
    title: "FEC — Candidates",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "FEC",
    access: "public",
    href: "https://www.fec.gov/data/browse-data?tab=candidates",
  },
  {
    slug: "fec-committees",
    title: "FEC — Committees",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "FEC",
    access: "public",
    href: "https://www.fec.gov/data/browse-data?tab=committees",
  },
  {
    slug: "fec-external-data-sources",
    title: "FEC — External Data Sources",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "FEC",
    access: "public",
    href: "https://www.fec.gov/data/browse-data?tab=external",
  },
  {
    slug: "fec-filings-reports",
    title: "FEC — Filings & Reports",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "FEC",
    access: "public",
    href: "https://www.fec.gov/data/browse-data?tab=filings",
  },
  {
    slug: "fec-loans-debts",
    title: "FEC — Loans & Debts",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "FEC",
    access: "public",
    href: "https://www.fec.gov/data/browse-data?tab=loans-debts",
  },
  {
    slug: "fec-main",
    title: "FEC — Main",
    summary: "Federal election filings. Source of record federally.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "FEC",
    access: "public",
    href: "https://www.fec.gov",
  },
  {
    slug: "lcps-school-board",
    title: "LCPS School Board",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "LCPS School Board",
    access: "public",
    href: "https://lcps.org/board",
  },
  {
    slug: "loudoun-county-board-of-supervisors",
    title: "Loudoun County Board of Supervisors",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Loudoun County Board of Supervisors",
    access: "public",
    href: "https://loudoun.gov/bos",
  },
  {
    slug: "loudoun-county-bos-legislative-archives-granicus",
    title: "Loudoun County BOS — Legislative Archives (Granicus)",
    summary: "Board video, agendas, and minutes.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Loudoun County BOS",
    access: "public",
    href: "https://loudoun.granicus.com/ViewPublisher.php?view_id=80",
  },
  {
    slug: "loudoun-county-foia-portal",
    title: "Loudoun County FOIA Portal",
    summary: "County FOIA portal. It does not file for you.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Loudoun County FOIA Portal",
    access: "public",
    href: "https://loudoun.gov/foia",
  },
  {
    slug: "loudoun-county-land-applications-arcgis",
    title: "Loudoun County Land Applications (ArcGIS)",
    summary: "Legislative land applications and related files.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Loudoun County Land Applications (ArcGIS)",
    access: "public",
    href: "https://experience.arcgis.com/experience/766df83879dd4e77900e03cb2198ee98",
  },
  {
    slug: "office-of-the-attorney-general-of-virginia",
    title: "Office of the Attorney General of Virginia",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Office of the Attorney General of Virginia",
    access: "public",
    href: "https://www.oag.state.va.us",
  },
  {
    slug: "rep-suhas-subramanyam-official-house-site-va-10",
    title: "Rep. Suhas Subramanyam — Official House Site (VA-10)",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Rep. Suhas Subramanyam",
    access: "public",
    href: "https://subramanyam.house.gov",
  },
  {
    slug: "usaspending-gov",
    title: "USAspending.gov",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "USAspending.gov",
    access: "public",
    href: "https://www.usaspending.gov",
  },
  {
    slug: "virginia-department-of-elections-citizen-portal",
    title: "Virginia Department of Elections — Citizen Portal",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia Department of Elections",
    access: "public",
    href: "https://www.elections.virginia.gov/citizen-portal/",
  },
  {
    slug: "virginia-department-of-elections-official-results",
    title: "Virginia Department of Elections — Official Results",
    summary: "Certified election results on the current elections site.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia Department of Elections",
    access: "public",
    href: "https://www.elections.virginia.gov/results/",
  },
  {
    slug: "virginia-general-assembly-portal",
    title: "Virginia General Assembly Portal",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia General Assembly Portal",
    access: "public",
    href: "https://vga.virginia.gov",
  },
  {
    slug: "virginia-historical-elections-database-pre-2024-results",
    title: "Virginia Historical Elections Database (pre-2024 results)",
    summary: "Pre-migration election results. District numbers are not the same geography across redistricting.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia Historical Elections Database (pre-2024 results)",
    access: "public",
    href: "https://historical.elections.virginia.gov",
  },
  {
    slug: "virginia-law-administrative-code",
    title: "Virginia Law — Administrative Code",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia Law",
    access: "public",
    href: "https://law.lis.virginia.gov/admincode/",
  },
  {
    slug: "virginia-law-code-of-virginia",
    title: "Virginia Law — Code of Virginia",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia Law",
    access: "public",
    href: "https://law.lis.virginia.gov/vacode/",
  },
  {
    slug: "virginia-law-constitution-of-virginia",
    title: "Virginia Law — Constitution of Virginia",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia Law",
    access: "public",
    href: "https://law.lis.virginia.gov/constitution/",
  },
  {
    slug: "virginia-legislative-information-system-lis",
    title: "Virginia Legislative Information System (LIS)",
    summary: "Current-session bills, history, and votes. Pre-2025 sessions are on the legacy system.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia Legislative Information System (LIS)",
    access: "public",
    href: "https://lis.virginia.gov",
  },
  {
    slug: "virginia-lis-legacy-system-pre-2025-sessions",
    title: "Virginia LIS — Legacy System (pre-2025 sessions)",
    summary: "Pre-2025 General Assembly sessions. The modern LIS does not hold these.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia LIS",
    access: "public",
    href: "https://legacylis.virginia.gov",
  },
  {
    slug: "virginia-local-governments-directory",
    title: "Virginia Local Governments Directory",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia Local Governments Directory",
    access: "public",
    href: "https://www.virginia.gov/local-government/",
  },
  {
    slug: "virginia-office-of-the-state-inspector-general",
    title: "Virginia Office of the State Inspector General",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia Office of the State Inspector General",
    access: "public",
    href: "https://www.osig.virginia.gov",
  },
  {
    slug: "virginia-open-data-portal-eva-procurement-data",
    title: "Virginia Open Data Portal — eVA Procurement Data",
    summary: "Official public record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia Open Data Portal",
    access: "public",
    href: "https://data.virginia.gov/dataset/eva-procurement-data-2024",
  },
  {
    slug: "virginia-sbe-campaign-finance-official-filings-source-of-record",
    title: "Virginia SBE Campaign Finance — Official Filings (source of record)",
    summary: "State campaign-finance filings. Source of record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "government",
    source: "Virginia SBE Campaign Finance",
    access: "public",
    href: "https://cfreports.elections.virginia.gov",
  },
  {
    slug: "abc-news",
    title: "ABC News",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "ABC News",
    access: "public",
    href: "https://abcnews.go.com",
  },
  {
    slug: "ap-news",
    title: "AP News",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "AP News",
    access: "public",
    href: "https://apnews.com",
  },
  {
    slug: "arlnow",
    title: "ARLnow",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "ARLnow",
    access: "public",
    href: "https://arlnow.com",
  },
  {
    slug: "augusta-free-press",
    title: "Augusta Free Press",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Augusta Free Press",
    access: "public",
    href: "https://augustafreepress.com",
  },
  {
    slug: "bacon-s-rebellion",
    title: "Bacon's Rebellion",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Bacon's Rebellion",
    access: "public",
    href: "https://www.baconsrebellion.com",
  },
  {
    slug: "blue-ridge-leader",
    title: "Blue Ridge Leader",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Blue Ridge Leader",
    access: "public",
    href: "https://blueridgeleader.com",
  },
  {
    slug: "c-span",
    title: "C-SPAN",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "C-SPAN",
    access: "public",
    href: "https://c-span.org",
  },
  {
    slug: "cardinal-news",
    title: "Cardinal News",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Cardinal News",
    access: "public",
    href: "https://cardinalnews.org",
  },
  {
    slug: "cbs-news",
    title: "CBS News",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "CBS News",
    access: "public",
    href: "https://cbsnews.com",
  },
  {
    slug: "cnn",
    title: "CNN",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "CNN",
    access: "public",
    href: "https://cnn.com",
  },
  {
    slug: "connection-newspapers",
    title: "Connection Newspapers",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Connection Newspapers",
    access: "public",
    href: "https://connectionnewspapers.com",
  },
  {
    slug: "courthouse-news-service",
    title: "Courthouse News Service",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Courthouse News Service",
    access: "public",
    href: "https://courthousenews.com",
  },
  {
    slug: "daily-press",
    title: "Daily Press",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Daily Press",
    access: "public",
    href: "https://dailypress.com",
  },
  {
    slug: "daily-signal",
    title: "Daily Signal",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Daily Signal",
    access: "public",
    href: "https://www.dailysignal.com",
  },
  {
    slug: "daily-wire",
    title: "Daily Wire",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Daily Wire",
    access: "public",
    href: "https://dailywire.com",
  },
  {
    slug: "data-center-dynamics",
    title: "Data Center Dynamics",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Data Center Dynamics",
    access: "public",
    href: "https://www.datacenterdynamics.com",
  },
  {
    slug: "fairfax-gop",
    title: "Fairfax GOP",
    summary: "Party organization. Not a newsroom.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Fairfax GOP",
    access: "public",
    href: "https://fairfaxgop.org",
  },
  {
    slug: "fauquier-now",
    title: "Fauquier Now",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Fauquier Now",
    access: "public",
    href: "https://fauquiernow.com",
  },
  {
    slug: "fox-5-dc",
    title: "FOX 5 DC",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "FOX 5 DC",
    access: "public",
    href: "https://fox5dc.com",
  },
  {
    slug: "fox-news",
    title: "Fox News",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Fox News",
    access: "public",
    href: "https://foxnews.com",
  },
  {
    slug: "free-beacon",
    title: "Free Beacon",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Free Beacon",
    access: "public",
    href: "https://freebeacon.com",
  },
  {
    slug: "insidenova",
    title: "InsideNoVa",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "InsideNoVa",
    access: "public",
    href: "https://insidenova.com",
  },
  {
    slug: "loudoun-now",
    title: "Loudoun Now",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Loudoun Now",
    access: "public",
    href: "https://loudounnow.com",
  },
  {
    slug: "loudoun-times-mirror",
    title: "Loudoun Times-Mirror",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Loudoun Times-Mirror",
    access: "public",
    href: "https://loudountimes.com",
  },
  {
    slug: "nbc-news",
    title: "NBC News",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "NBC News",
    access: "public",
    href: "https://nbcnews.com",
  },
  {
    slug: "nbc-washington-loudoun",
    title: "NBC Washington Loudoun",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "NBC Washington Loudoun",
    access: "public",
    href: "https://nbcwashington.com",
  },
  {
    slug: "new-york-times",
    title: "New York Times",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "New York Times",
    access: "public",
    href: "https://nytimes.com",
  },
  {
    slug: "northern-virginia-magazine",
    title: "Northern Virginia Magazine",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Northern Virginia Magazine",
    access: "public",
    href: "https://northernvirginiamag.com",
  },
  {
    slug: "patch-loudoun",
    title: "Patch Loudoun",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Patch Loudoun",
    access: "public",
    href: "https://patch.com/virginia/leesburg",
  },
  {
    slug: "politico",
    title: "Politico",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Politico",
    access: "public",
    href: "https://politico.com",
  },
  {
    slug: "prince-william-times",
    title: "Prince William Times",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Prince William Times",
    access: "public",
    href: "https://princewilliamtimes.com",
  },
  {
    slug: "reason",
    title: "Reason",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Reason",
    access: "public",
    href: "https://reason.com",
  },
  {
    slug: "reuters",
    title: "Reuters",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Reuters",
    access: "public",
    href: "https://reuters.com",
  },
  {
    slug: "richmond-times-dispatch",
    title: "Richmond Times-Dispatch",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Richmond Times-Dispatch",
    access: "public",
    href: "https://richmond.com",
  },
  {
    slug: "the-center-square-virginia",
    title: "The Center Square (Virginia)",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "The Center Square (Virginia)",
    access: "public",
    href: "https://thecentersquare.com/virginia",
  },
  {
    slug: "virginia-business",
    title: "Virginia Business",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Virginia Business",
    access: "public",
    href: "https://www.virginiabusiness.com",
  },
  {
    slug: "virginia-mercury",
    title: "Virginia Mercury",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Virginia Mercury",
    access: "public",
    href: "https://virginiamercury.com",
  },
  {
    slug: "virginia-scope",
    title: "Virginia Scope",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Virginia Scope",
    access: "public",
    href: "https://virginiascope.com",
  },
  {
    slug: "virginian-pilot",
    title: "Virginian-Pilot",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Virginian-Pilot",
    access: "public",
    href: "https://pilotonline.com",
  },
  {
    slug: "vpap-vanews",
    title: "VPAP VaNews",
    summary: "News roundup. Convenience, not a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "VPAP VaNews",
    access: "public",
    href: "https://vpap.org/vanews",
  },
  {
    slug: "vpm",
    title: "VPM",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "VPM",
    access: "public",
    href: "https://vpm.org",
  },
  {
    slug: "washington-business-journal",
    title: "Washington Business Journal",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Washington Business Journal",
    access: "public",
    href: "https://www.bizjournals.com/washington/",
  },
  {
    slug: "washington-post",
    title: "Washington Post",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Washington Post",
    access: "public",
    href: "https://washingtonpost.com",
  },
  {
    slug: "winchester-star",
    title: "Winchester Star",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "Winchester Star",
    access: "public",
    href: "https://www.winchesterstar.com",
  },
  {
    slug: "wjla-abc7-loudoun",
    title: "WJLA / ABC7 Loudoun",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "WJLA / ABC7 Loudoun",
    access: "public",
    href: "https://wjla.com/news/local/loudoun-county",
  },
  {
    slug: "wset",
    title: "WSET",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "WSET",
    access: "public",
    href: "https://wset.com",
  },
  {
    slug: "wtop",
    title: "WTOP",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "WTOP",
    access: "public",
    href: "https://wtop.com",
  },
  {
    slug: "wusa9",
    title: "WUSA9",
    summary: "Newsroom this desk reads. Prefer reporting that cites a primary record.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "news",
    source: "WUSA9",
    access: "public",
    href: "https://wusa9.com",
  },
  {
    slug: "america-first-legal",
    title: "America First Legal",
    summary: "Public research door. Not a substitute for the official filing.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "America First Legal",
    access: "public",
    href: "https://aflegal.org",
  },
  {
    slug: "citizen-portal-virginia",
    title: "Citizen Portal — Virginia",
    summary: "Third-party bill tracker. Not LIS.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "Citizen Portal",
    access: "public",
    href: "https://citizenportal.ai/feed/2309/virginia",
  },
  {
    slug: "data-republican-federal-grant-search",
    title: "Data Republican — Federal Grant Search",
    summary: "Public research door. Not a substitute for the official filing.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "Data Republican",
    access: "public",
    href: "https://datarepublican.com/award_search/",
  },
  {
    slug: "go-virginia",
    title: "GO Virginia",
    summary: "Public research door. Not a substitute for the official filing.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "GO Virginia",
    access: "public",
    href: "https://govirginia.org",
  },
  {
    slug: "influencewatch-educational-guide",
    title: "InfluenceWatch — Educational Guide",
    summary: "Public research door. Not a substitute for the official filing.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "InfluenceWatch",
    access: "public",
    href: "https://www.influencewatch.org/about-us/educational-guide/",
  },
  {
    slug: "influencewatch-groups",
    title: "InfluenceWatch — Groups",
    summary: "Public research door. Not a substitute for the official filing.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "InfluenceWatch",
    access: "public",
    href: "https://www.influencewatch.org/groups/",
  },
  {
    slug: "influencewatch-influence-networks",
    title: "InfluenceWatch — Influence Networks",
    summary: "Public research door. Not a substitute for the official filing.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "InfluenceWatch",
    access: "public",
    href: "https://www.influencewatch.org/influence-networks/",
  },
  {
    slug: "influencewatch-people",
    title: "InfluenceWatch — People",
    summary: "Public research door. Not a substitute for the official filing.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "InfluenceWatch",
    access: "public",
    href: "https://www.influencewatch.org/people/",
  },
  {
    slug: "national-archives",
    title: "National Archives",
    summary: "Public research door. Not a substitute for the official filing.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "National Archives",
    access: "public",
    href: "https://www.archives.gov",
  },
  {
    slug: "opensecrets",
    title: "OpenSecrets",
    summary: "Federal money-in-politics door. Convenience, not a substitute for FEC.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "OpenSecrets",
    access: "public",
    href: "https://www.opensecrets.org",
  },
  {
    slug: "vote-smart-virginia-key-votes-rss",
    title: "Vote Smart — Virginia Key Votes (RSS)",
    summary: "Key-vote feed. Not the official roll call.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "Vote Smart",
    access: "public",
    href: "http://votesmart.org/rss/key-votes/VA",
  },
  {
    slug: "youtube",
    title: "YouTube",
    summary: "Public research door. Not a substitute for the official filing.",
    date: "2026-08-21",
    displayDate: "Standing source",
    kind: "research-tool",
    source: "YouTube",
    access: "public",
    href: "https://www.youtube.com",
  },
];

export function libraryBySlug(slug: string) {
  return LIBRARY.find((i) => i.slug === slug);
}
