/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R2027RouteImport } from './routes/2027'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CountiesRouteImport } from './routes/counties'
import { Route as DelegatesRouteImport } from './routes/delegates'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SenatorsRouteImport } from './routes/senators'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as CountiesIndexRouteImport } from './routes/counties.index'
import { Route as CountiesLoudounRouteImport } from './routes/counties.loudoun'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations.index'
import { Route as InvestigationsSlugRouteImport } from './routes/investigations.$slug'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryFoiaRouteImport } from './routes/library.foia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R2027Route = R2027RouteImport.update({
  id: '/2027',
  path: '/2027',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CountiesRoute = CountiesRouteImport.update({
  id: '/counties',
  path: '/counties',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegatesRoute = DelegatesRouteImport.update({
  id: '/delegates',
  path: '/delegates',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SenatorsRoute = SenatorsRouteImport.update({
  id: '/senators',
  path: '/senators',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const CountiesIndexRoute = CountiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountiesRoute,
} as any)
const CountiesLoudounRoute = CountiesLoudounRouteImport.update({
  id: '/loudoun',
  path: '/loudoun',
  getParentRoute: () => CountiesRoute,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestigationsRoute,
} as any)
const InvestigationsSlugRoute = InvestigationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InvestigationsRoute,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryFoiaRoute = LibraryFoiaRouteImport.update({
  id: '/foia',
  path: '/foia',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/2027': typeof R2027Route
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/counties': typeof CountiesRouteWithChildren
  '/delegates': typeof DelegatesRoute
  '/investigations': typeof InvestigationsRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/news': typeof NewsRoute
  '/senators': typeof SenatorsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/counties/loudoun': typeof CountiesLoudounRoute
  '/investigations/$slug': typeof InvestigationsSlugRoute
  '/library/foia': typeof LibraryFoiaRoute
  '/articles/': typeof ArticlesIndexRoute
  '/counties/': typeof CountiesIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/2027': typeof R2027Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/delegates': typeof DelegatesRoute
  '/news': typeof NewsRoute
  '/senators': typeof SenatorsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/counties/loudoun': typeof CountiesLoudounRoute
  '/investigations/$slug': typeof InvestigationsSlugRoute
  '/library/foia': typeof LibraryFoiaRoute
  '/articles': typeof ArticlesIndexRoute
  '/counties': typeof CountiesIndexRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/2027': typeof R2027Route
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/counties': typeof CountiesRouteWithChildren
  '/delegates': typeof DelegatesRoute
  '/investigations': typeof InvestigationsRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/news': typeof NewsRoute
  '/senators': typeof SenatorsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/counties/loudoun': typeof CountiesLoudounRoute
  '/investigations/$slug': typeof InvestigationsSlugRoute
  '/library/foia': typeof LibraryFoiaRoute
  '/articles/': typeof ArticlesIndexRoute
  '/counties/': typeof CountiesIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/2027'
    | '/about'
    | '/articles'
    | '/contact'
    | '/counties'
    | '/delegates'
    | '/investigations'
    | '/library'
    | '/news'
    | '/senators'
    | '/articles/$slug'
    | '/counties/loudoun'
    | '/investigations/$slug'
    | '/library/foia'
    | '/articles/'
    | '/counties/'
    | '/investigations/'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/2027'
    | '/about'
    | '/contact'
    | '/delegates'
    | '/news'
    | '/senators'
    | '/articles/$slug'
    | '/counties/loudoun'
    | '/investigations/$slug'
    | '/library/foia'
    | '/articles'
    | '/counties'
    | '/investigations'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/2027'
    | '/about'
    | '/articles'
    | '/contact'
    | '/counties'
    | '/delegates'
    | '/investigations'
    | '/library'
    | '/news'
    | '/senators'
    | '/articles/$slug'
    | '/counties/loudoun'
    | '/investigations/$slug'
    | '/library/foia'
    | '/articles/'
    | '/counties/'
    | '/investigations/'
    | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R2027Route: typeof R2027Route
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ContactRoute: typeof ContactRoute
  CountiesRoute: typeof CountiesRouteWithChildren
  DelegatesRoute: typeof DelegatesRoute
  InvestigationsRoute: typeof InvestigationsRouteWithChildren
  LibraryRoute: typeof LibraryRouteWithChildren
  NewsRoute: typeof NewsRoute
  SenatorsRoute: typeof SenatorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2027': {
      id: '/2027'
      path: '/2027'
      fullPath: '/2027'
      preLoaderRoute: typeof R2027RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counties': {
      id: '/counties'
      path: '/counties'
      fullPath: '/counties'
      preLoaderRoute: typeof CountiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegates': {
      id: '/delegates'
      path: '/delegates'
      fullPath: '/delegates'
      preLoaderRoute: typeof DelegatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senators': {
      id: '/senators'
      path: '/senators'
      fullPath: '/senators'
      preLoaderRoute: typeof SenatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/counties/': {
      id: '/counties/'
      path: '/'
      fullPath: '/counties/'
      preLoaderRoute: typeof CountiesIndexRouteImport
      parentRoute: typeof CountiesRoute
    }
    '/counties/loudoun': {
      id: '/counties/loudoun'
      path: '/loudoun'
      fullPath: '/counties/loudoun'
      preLoaderRoute: typeof CountiesLoudounRouteImport
      parentRoute: typeof CountiesRoute
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/'
      fullPath: '/investigations/'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof InvestigationsRoute
    }
    '/investigations/$slug': {
      id: '/investigations/$slug'
      path: '/$slug'
      fullPath: '/investigations/$slug'
      preLoaderRoute: typeof InvestigationsSlugRouteImport
      parentRoute: typeof InvestigationsRoute
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/foia': {
      id: '/library/foia'
      path: '/foia'
      fullPath: '/library/foia'
      preLoaderRoute: typeof LibraryFoiaRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface CountiesRouteChildren {
  CountiesLoudounRoute: typeof CountiesLoudounRoute
  CountiesIndexRoute: typeof CountiesIndexRoute
}

const CountiesRouteChildren: CountiesRouteChildren = {
  CountiesLoudounRoute: CountiesLoudounRoute,
  CountiesIndexRoute: CountiesIndexRoute,
}

const CountiesRouteWithChildren = CountiesRoute._addFileChildren(
  CountiesRouteChildren,
)

interface InvestigationsRouteChildren {
  InvestigationsSlugRoute: typeof InvestigationsSlugRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
}

const InvestigationsRouteChildren: InvestigationsRouteChildren = {
  InvestigationsSlugRoute: InvestigationsSlugRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
}

const InvestigationsRouteWithChildren = InvestigationsRoute._addFileChildren(
  InvestigationsRouteChildren,
)

interface LibraryRouteChildren {
  LibraryFoiaRoute: typeof LibraryFoiaRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryFoiaRoute: LibraryFoiaRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R2027Route: R2027Route,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  ContactRoute: ContactRoute,
  CountiesRoute: CountiesRouteWithChildren,
  DelegatesRoute: DelegatesRoute,
  InvestigationsRoute: InvestigationsRouteWithChildren,
  LibraryRoute: LibraryRouteWithChildren,
  NewsRoute: NewsRoute,
  SenatorsRoute: SenatorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
