/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as InvestigationsIndexRouteImport } from './routes/investigations.index'
import { Route as InvestigationsSlugRouteImport } from './routes/investigations.$slug'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryFoiaRouteImport } from './routes/library.foia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const InvestigationsIndexRoute = InvestigationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestigationsRoute,
} as any)
const InvestigationsSlugRoute = InvestigationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InvestigationsRoute,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryFoiaRoute = LibraryFoiaRouteImport.update({
  id: '/foia',
  path: '/foia',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/investigations': typeof InvestigationsRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/investigations/$slug': typeof InvestigationsSlugRoute
  '/library/foia': typeof LibraryFoiaRoute
  '/articles/': typeof ArticlesIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/investigations/$slug': typeof InvestigationsSlugRoute
  '/library/foia': typeof LibraryFoiaRoute
  '/articles': typeof ArticlesIndexRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/contact': typeof ContactRoute
  '/investigations': typeof InvestigationsRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/investigations/$slug': typeof InvestigationsSlugRoute
  '/library/foia': typeof LibraryFoiaRoute
  '/articles/': typeof ArticlesIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/contact'
    | '/investigations'
    | '/library'
    | '/articles/$slug'
    | '/investigations/$slug'
    | '/library/foia'
    | '/articles/'
    | '/investigations/'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/articles/$slug'
    | '/investigations/$slug'
    | '/library/foia'
    | '/articles'
    | '/investigations'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles'
    | '/contact'
    | '/investigations'
    | '/library'
    | '/articles/$slug'
    | '/investigations/$slug'
    | '/library/foia'
    | '/articles/'
    | '/investigations/'
    | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ContactRoute: typeof ContactRoute
  InvestigationsRoute: typeof InvestigationsRouteWithChildren
  LibraryRoute: typeof LibraryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/'
      fullPath: '/investigations/'
      preLoaderRoute: typeof InvestigationsIndexRouteImport
      parentRoute: typeof InvestigationsRoute
    }
    '/investigations/$slug': {
      id: '/investigations/$slug'
      path: '/$slug'
      fullPath: '/investigations/$slug'
      preLoaderRoute: typeof InvestigationsSlugRouteImport
      parentRoute: typeof InvestigationsRoute
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/foia': {
      id: '/library/foia'
      path: '/foia'
      fullPath: '/library/foia'
      preLoaderRoute: typeof LibraryFoiaRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface InvestigationsRouteChildren {
  InvestigationsSlugRoute: typeof InvestigationsSlugRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
}

const InvestigationsRouteChildren: InvestigationsRouteChildren = {
  InvestigationsSlugRoute: InvestigationsSlugRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
}

const InvestigationsRouteWithChildren = InvestigationsRoute._addFileChildren(
  InvestigationsRouteChildren,
)

interface LibraryRouteChildren {
  LibraryFoiaRoute: typeof LibraryFoiaRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryFoiaRoute: LibraryFoiaRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  ContactRoute: ContactRoute,
  InvestigationsRoute: InvestigationsRouteWithChildren,
  LibraryRoute: LibraryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
